### ISSUE TITLE
mrlesmithjr.netplan removes existing netplan config

### ISSUE THREAD

**Issue by giancarlo3g** [giancarlo3g/ansible-basics#1]
netplan removes exiting config from target

**Comment by giancarlo3g** [comment]
netplan_remove_existing has to be set to "no" so original network configuration is not removed from target.
Final yaml looks:

```
---
- hosts: host
  vars:
  tasks:
  roles:
    - role: mrlesmithjr.netplan
      become: yes
      netplan_enabled: true
      netplan_remove_existing: no
      netplan_config_file: /etc/netplan/my_netplan.yaml
      netplan_renderer: networkd 
      netplan_configuration:
        network:
          version: 2
          bridges:
            br-mgmt:
              addresses:
                - 192.168.1.1/24 
            br-wan:
              dhcp4: yes
      netplan_apply: True
```
